### ISSUE TITLE
[Design] #1. 메인페이지 최상단 구성

### ISSUE THREAD

**Issue by raxchaz** [cca-ffodregamdi/running-hi-frontend#4]
### 🧞‍♀️ 제작할 페이지
- **Main Page** 

<br>

### 🧞‍♀️ 제작해야 할 부분
- 최상단 페이지 [1920*1080 기준] 

<br>

### 🧞‍♀️ 구현 계획
1. 페이지 내 각각 어떤 atom / molecules / organisms들이 필요한지 파악
2. **상향식 설계** [main -> organisms -> molecules -> atom] 순서로 제작
3. 너무 넓은 레이아웃을 피하여 [1750*900] 안에 프레임들이 배치되도록 제작

<br>

### ✅ 체크 사항
- [x] header
- [x] sideBar

<br>

### 👍피드백 | 참고 + 전달사항

<br>

**Comment by fakerdeft** [comment]
지도 배치에 대한 고민을 좀 더 해봐야겠네요! 이건 모여서 다시 얘기해볼까요?
