### ISSUE TITLE
[MainPage] #2. 헤더 구성

### ISSUE THREAD

**Issue by raxchaz** [cca-ffodregamdi/running-hi-frontend#5]
### 🧞‍♀️ 제작할 페이지
- **MainPage**

### 🧞‍♀️ 제작해야 할 부분
- **MainPage - Header**

### 🧞‍♀️ 구현 레퍼런스 

![image](https://github.com/cca-ffodregamdi/running-hi-frontend/assets/119282494/63333744-0d33-4578-86a2-648da0a27531)
![image](https://github.com/cca-ffodregamdi/running-hi-frontend/assets/119282494/0b39b45f-6672-4055-9fe5-0510b18fcde6)

- 된다면 이렇게 가져가고 싶은데 로고는 아직 미정입니다!
<br>

### ✅ 체크 사항
- [x] 헤더에 signup 버튼이 굳이 필요한지 체크하기 [로그인 들어가면 비회원은 가입 바로 넘어가니까]
- [x] 비로그인 유저가 볼 수 있는 헤더에 뭐가 필요한지 곰곰히 더 생각해보기 - .. 사용자 경험은 중요! 
       ㄴ 저 정도면 충분할 것 같아서 일단 저대로 구현하겠습니다!
- [x] 헤더 부분에 [help] 버튼 고려 or [about] 버튼 -> 메인 화면에 지도 밖에 없으면 뭐지 싶을지도 몰루 
- [x] 헤더에 [about] 버튼 or 메인 페이지에 줄글 설명 둘 중 하나 선택

**Comment by fakerdeft** [comment]
일단 전 파/흰 조합이 좀 더 눈에 들어오는 것 같습니다!!

**Comment by Subak-Uncle** [comment]
많은 고민하신 게 눈에 보이네요ㅠㅠ 고생많으셨습니다! [헬프]가 디자인 상 더 좋을 것 같지만, 회의 때 같이 논의해보아요!!

**Comment by raxchaz** [comment]
> 많은 고민하신 게 눈에 보이네요ㅠㅠ 고생많으셨습니다! [헬프]가 디자인 상 더 좋을 것 같지만, 회의 때 같이 논의해보아요!!

저 메인 웹 헤더는 비로그인 유저가 보는 화면이라 도움보다는 
사이트에 대한 설명이 나와있는 About이 맞는 것 같아서 해당 버튼을 제작했어요!
Help는 로그인 유저에게 보여지는 웹 화면에 배치하면 어떨까요? 
 어차피 햄버거 바에 FAQ가 있으니까 햄버거 바에 아주 숨겨버려도 좋을 것 같아요

**Comment by Dylan-SonJungin** [comment]
오!! 디자인 너무 좋습니다^0^ 상태에 따라 색이 변하는 아이디어 좋은 것 같습니다!!
